- block:
    - name: Run system update and upgrade
      apt:
        upgrade: dist
        update_cache: yes
    - name: Install basic packages
      ansible.builtin.apt:
        pkg:
          - git
          - curl
          - wget
          - tmux
          - python3-pip
          - nvidia-jetpack
          - bat
          - python3-selinux
          - selinux-utils
          - selinux-policy-default
    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled
      register: selinux_results
    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_md5: no
      register: reboot_required_file
    - name: Reboot the server (if required).
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true or selinux_results.reboot_required == true
  become: yes
