- name: Install lxde and lightdm
  ansible.builtin.apt:
    pkg:
      - lightdm
      - lxde
  become: yes
- name: Remove gdm3
  ansible.builtin.apt:
    name: gdm3
    state: absent
    purge: true
  become: yes
