# These two additional packages are required for snap to be able to run without 
# warnings
- name: Install snapd, squashfuse, and fuse
  apt:
    pkg:
      - snapd
      - fuse
      - squashfuse
    update_cache: yes
  become: yes
- name: Install neovim SNAP
  snap:
    name: nvim
    state: present
    classic: true
  become: yes
- name: Install AstroNvim and user configs
  become: no
  block:
    - name: Create .config folder
      become: no
      ansible.builtin.file:
        path: /home/xander/.config
        state: directory
        mode: '0750'
    - name: Install AstroVim git repo
      git:
        repo: 'https://github.com/AstroNvim/AstroNvim'
        dest: /home/xander/.config/nvim
    - name: Copy nvim user configs
      copy:
        src: files/nvim-user-config/
        dest: /home/xander/.config/nvim/lua/user/
